name: 2022-ubc-fatiando
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - jupyterlab
  - xarray
  - cartopy
  - netcdf4
  - pygmt
  - pyproj
  # To serve slides
  - livereload
  # Fatiando packages
  - pooch==1.6.0
  - verde==1.7.0
  - boule==0.4.0
  - ensaio==0.4.0
  - harmonica==0.5.0
  # To speed up Verde
  - pykdtree
  - numba
  # SimPEG
  - simpeg
